workspace = { members = ["members/spawn-blocking-lib"] }
[package]
name = "spawn-blocking-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
