workspace = { members = ["members/echo-server-lib", "members/echo-server-main"] }
[package]
name = "echo-server-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
