workspace = { members = ["members/basic-router-lib"] }
[package]
name = "basic-router-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
