workspace = { members = ["members/many-requests-surf-lib", "members/many-requests-surf-main"] }
[package]
name = "many-requests-surf-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
