[package]
name = "many-requests-surf-main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-requests-surf={path="../many-requests-surf-lib"}
async-std="1.7"